name: London Tube - Group 12
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' 

    - name: Install dependencies
      run: |
        pip install -e .[dev]  # Install package + dev dependencies from pyproject.toml
        pip install pytest


    - name: Test with pytest
      run: |
        pytest
